### ISSUE TITLE
Beyond @login - Enable data exchange between web applications and atProtocol 

### ISSUE THREAD

**Issue by VJag** [atsign-foundation/at_login#9]
### Is your feature request related to a problem? Please describe.

If @login is implemented "https://github.com/atsign-foundation/at_login/issues/8" then the next logical step is to enable data exchange.

### Describe the solution you'd like
The solution that empowers the data exchange should have the following characteristics:

1. A Clear understanding of the roles of every party involved 

                        The following are the parties involved:

- atApp
- atSign
- atUser
- Web application

2. Easy and intuitive API to facilitate the data exchange
3. Platform-independent data format
4. Understandable schema of the data 

Collections library is a library on atProtocol that happens to have some of the attributes of the desired aspects of the solution.
In this ticket, we would be extending the collections library as a way to facilitate seamless data exchange.

### Task list

- [x] Extend collections library
- [x] Propose a design for the semantics of data exchange
- [x] Implement the proposal

### Additional context
https://docs.google.com/document/d/1sdEuA3L68b3182q-e6UVxGeiSb-J2MEvjSsnxdmjFlk/edit?usp=sharing

**Comment by VJag** [comment]
In PR61 spent at least 8 story points on improving the collections library.  The code is available in the branch "collections_refactored". A [document](https://docs.google.com/document/d/1tpLtHIq-PxiEOAEuexx3mFKCRNiyse8HDREDCpd9FB8/edit?usp=sharing) is written to help to get easily started with collections.

**Comment by VJag** [comment]
Pending work on this task is to:

1. Revisit support for metadata
2. Add experimental tag
3. Merge to trunk

3SP to 5SP In PR 62 is enough to take care of the pending tasks.

**Comment by VJag** [comment]
- A library that facilitates data exchange has been developed. The library contains ways to:

1. Send data share requests
2. Acknowledge the data share requests
3. List sent data share requests
4. List receive data share requests
5. Fulfill a data share request (Fulfillment is done by apps by they use the library for the communication)

**Comment by sitaram-kalluri** [comment]
The changes are pushed into https://github.com/atsign-foundation/at_demos/tree/at_data_share
